### ISSUE TITLE
Last Played field not updated in Library view after song plays

### ISSUE THREAD

**Issue by robbat2** [anonbeat/guayadeque#62]
If a file is not writable to the player (eg on read-only media, or simply no filesystem permissions), then the `Last Played` data is never updated. The statistic should be tracked outside of the file for this purpose.

**Comment by anonbeat** [comment]
Could not reproduce it here... I played some tracks that have not write permissions and the Playcount and the last played are updated correctly. Maybe you have enabled in your collection settings (Preferences->Collections->Your Collection ) 'Embed rating, play count and labels' 

You should disable it for this collection as it is read only.

**Comment by robbat2** [comment]
Regardless of that setting, it should still be tracked. If the file is not writable, don't embed it, but do still track outside the file.

**Comment by anonbeat** [comment]
I just did a test again to be sure and this seems to be working fine. PlayCount and LastPlayed is updated even with not writeable media. Its tracked in database and if option is checked in file. If write of tags fails puts a warning in the console but the database is updated.

Please let me know if that is not happening for you because then seems there is another problem that I cant reproduce it here.

**Comment by robbat2** [comment]
Meant to come back to this, this seems to be some sort of display refresh bug.
After the song ends, if it's visible in the `my music` library view, then that mention of the last play time is not updated until the search query causes a refresh.

**Comment by anonbeat** [comment]
Please check if https://github.com/anonbeat/guayadeque/commit/48aad0c2a4ae01ab3f79227a9b1cf7b9270fedca fixes the issue

**Comment by robbat2** [comment]
Much better :-). Will open a new issue for a minor further tweak I see.
